apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: paulthedev007/hello-world:1.3.0  # Your Spring Boot Docker image
          ports:
            - containerPort: 8080  # Spring Boot default port
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"  # You can add Spring-specific profiles here, if needed
