apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 30080  # Exposing port 80 for external access (or choose your preferred port)
      targetPort: 8080  # Internal port used by the Spring Boot app
  type: ClusterIP  # Can change to NodePort if you want external access
